FROM python:3.9
RUN pip install --upgrade pip

COPY ./requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

COPY ./src/ /home/app/src/

WORKDIR /home/app/

CMD ["pytest", "-v"]